<?php namespace Russvet\Api\Services;

/**
 * Данный класс используется для получения списка позиций.
 * Class Position
 * @package Russvet\Api\Services
 */
class Position extends \Russvet\Api\Api
{
	CONST CATEGORY_TYPE_CUSTOM = 'custom'; // позиции, которые привозятся под заказ
	CONST CATEGORY_TYPE_INSTOCK = 'instock'; // позиции, относящиеся к складской номенклатуре на выбранном складе
	
    public function __construct()
    {
        parent::__construct();
        $this->data["uriApi"] = "/rs/position";
    }

    /**
     * установить ID склада
     * @param string $id
     */
    public function setIdStock(string $id): void
    {
        $this->uriRequest["stockId"] = $id;
    }

	/**
     * установить категорию позиции
     * @param string $category
     */
    public static function getCategoryTypes(): array
    {
        return [
			self::CATEGORY_TYPE_CUSTOM,
			self::CATEGORY_TYPE_INSTOCK,
		];
    }

    /**
     * установить категорию позиции
     * @param string $category
     */
    public function setCategory(string $category): void
    {
        $this->uriRequest["categoryId"] = $category;
    }

    /**
     * установить пагинацию страницы
     * @param string $page
     */
    public function setPage(string $page): void
    {
        $this->requestData["page"] = $page;
    }

    public function send()
    {
        $this->data["uriApi"] = $this->data["uriApi"]."/".$this->uriRequest["stockId"]."/".$this->uriRequest["categoryId"];
        return parent::send(); // TODO: Change the autogenerated stub
    }
}