<?php namespace Russvet\Api\Services;


/**
 * Данный класс используется для получения информации о ценах по выбранной позиции.
 * Class Price
 * @package Russvet\Api\Services
 */
class Price extends \Russvet\Api\Api
{
    public function __construct()
    {
        parent::__construct();
        $this->data["uriApi"] = "/rs/price";
    }

    /**
     * установить код позиции
     * @param string $code
     */
    public function setCodePosition(string $code): void
    {
        $this->uriRequest["codePosition"] = $code;
    }

    public function send()
    {
        $this->data["uriApi"] = $this->data["uriApi"]."/".$this->uriRequest["codePosition"];
        return parent::send(); // TODO: Change the autogenerated stub
    }
}