<?php namespace Russvet\Api\Services;

/**
 * Данный класс используется для получения информации о доступном количестве выбранной позиции на выбранном складе.
 * Class Residue
 * @package Russvet\Api\Services
 */
class Residue extends \Russvet\Api\Api
{
    public function __construct()
    {
        parent::__construct();
        $this->data["uriApi"] = "/rs/residue";
    }

    /**
     * установить ID склада
     * @param string $stockId
     */
    public function setIdStock(string $stockId): void
    {
        $this->uriRequest["stockId"] = $stockId;
    }

    /**
     * установить код позиции
     * @param string $code
     */
    public function setCodePosition(string $code): void
    {
        $this->uriRequest["codePosition"] = $code;
    }

    public function send()
    {
        $this->data["uriApi"] = $this->data["uriApi"]."/".$this->uriRequest["stockId"]."/".$this->uriRequest["codePosition"];
        return parent::send(); // TODO: Change the autogenerated stub
    }
}