<?php namespace Russvet\Api\Services;

/**
 * Данный класс используется для получения основной информации о позиции
 * а также технических характеристик в формате ETIM и ссылок на изображения без водяных знаков.
 * Class Specs
 * @package Russvet\Api\Services
 */
class Specs extends \Russvet\Api\Api
{
    public function __construct()
    {
        parent::__construct();
        $this->data["uriApi"] = "/rs/specs";
    }

    /**
     * установить код позиции
     * @param string $code
     */
    public function setCodePosition(string $code): void
    {
        $this->uriRequest["codePosition"] = $code;
    }

    public function send()
    {
        $this->data["uriApi"] = $this->data["uriApi"]."/".$this->uriRequest["codePosition"];
        return parent::send(); // TODO: Change the autogenerated stub
    }
}